# Generated by Django 2.0.4 on 2018-04-10 14:55

import account.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='部门名称')),
                ('active', models.BooleanField(default=True)),
                ('order', account.fields.OrderField(blank=True)),
            ],
            options={
                'verbose_name': '部门',
                'verbose_name_plural': '部门',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', '男'), ('F', '女')], max_length=10, verbose_name='性别')),
                ('phone', models.PositiveIntegerField(blank=True, verbose_name='联系方式')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='出生时间')),
                ('status', models.CharField(choices=[('ON', '在职'), ('OUT', '离职')], max_length=10, verbose_name='人员状态')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Profiles', to='account.Department')),
            ],
        ),
        migrations.CreateModel(
            name='UserPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='职位')),
                ('active', models.BooleanField(default=True)),
                ('order', account.fields.OrderField(blank=True)),
            ],
            options={
                'verbose_name': '岗位',
                'verbose_name_plural': '岗位',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_Profile', to='account.UserPost'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
