# Generated by Django 2.0.4 on 2018-04-10 15:24

import account.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['order'], 'verbose_name': '部门', 'verbose_name_plural': '部门管理'},
        ),
        migrations.AlterField(
            model_name='department',
            name='active',
            field=models.BooleanField(default=True, verbose_name='是否启用'),
        ),
        migrations.AlterField(
            model_name='department',
            name='order',
            field=account.fields.OrderField(blank=True, verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='userpost',
            name='active',
            field=models.BooleanField(default=True, verbose_name='是否启用'),
        ),
        migrations.AlterField(
            model_name='userpost',
            name='order',
            field=account.fields.OrderField(blank=True, verbose_name='排序'),
        ),
    ]
