# Generated by Django 2.0.4 on 2018-04-10 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20180410_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Profiles', to='account.Department', verbose_name='部门'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_Profile', to='account.UserPost', verbose_name='岗位'),
        ),
    ]
