# Generated by Django 2.0.4 on 2018-04-11 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20180410_2327'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userpost',
            options={'ordering': ['order'], 'verbose_name': '岗位', 'verbose_name_plural': '岗位管理'},
        ),
    ]
