# Generated by Django 2.0.4 on 2018-04-16 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20180411_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='出生日期'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('ON', '在职'), ('OUT', '离职')], help_text='员工是否在职', max_length=10, verbose_name='人员状态'),
        ),
    ]
